function setFigProps

width = 8.5;     % Width in inches
height = 11;    % Height in inches
alw = 0.75;    % AxesLineWidth
fsz = 12;      % Fontsize
lw = 1.5;      % LineWidth
msz = 8;       % MarkerSize);
Defpos = get(0,'DefaultFigurePosition');
Defsize = [1, 1, width, height];

set(0, 'DefaultFigureColor', 'white', ...
'DefaultAxesLineWidth', 1, ...
'DefaultAxesColor', 'none', ...
'DefaultAxesFontSize', 20, ...
'DefaultAxesFontName', 'AvantGarde', ...
'DefaultAxesLayer', 'Bottom', ...
'DefaultAxesXcolor', [0, 0, 0], ...
'DefaultAxesYcolor', [0, 0, 0], ...
'DefaultAxesZcolor', [0, 0, 0], ...
'DefaultAxesColorOrder',[0.1804 0.1922 0.5725; 0.5569 0.1098 0.2510], ...
'DefaultTextColor', [0, 0, 0], ...
'DefaultTextFontSize', 20, ...
'DefaultTextFontName', 'AvantGarde', ...
'DefaultTextVerticalAlignment', 'middle', ...
'DefaultTextHorizontalAlignment', 'left', ...
'DefaultLineLineWidth',lw, ...
'DefaultLineMarkerSize',msz, ...
'DefaultLineLineWidth',lw, ...
'DefaultLineMarkerSize',msz, ...
'DefaultFigurePaperUnits','inches', ...
'DefaultFigurePaperType','A4');

%'DefaultFigurePaperPosition', Defsize, ...
% AvantGarde
%cmunss
